### ISSUE TITLE
Is this project still under development? 

### ISSUE THREAD

**Issue by kidhasmoxy** [sheaffej/otto-ui#2]
The rules engine you've created seems to be the missing piece of a home automation system centered on Home Assistant. Are you still working on the UI? I'm thinking that this could come to mirror something like webcore (https://www.webcore.co/) in creating an easy to use system for establishing simple to complex automations that are much more user friendly to manage than the built in automations.

**Comment by sheaffej** [comment]
Hi @kidhasmoxy, thanks for reaching out. Sorry for the delay in replying, I seem to have messed up my GH notifications when I changed jobs and didn't notice this until now. 

I'm not actively developing this right now as it meets my specific smart home needs as is, and the Home Assistant team has also been putting a lot of effort into their automation UX lately. I'm hoping Home Assistant catches up with a visual rules editor. Also Angular isn't one of my core competencies, and it's changing quite fast so it's hard for me to keep up on the new Angular APIs.

Hopefully the design and/or even the code (although I'm sure it's not the best Angular code) will help others if only for inspiration.
